// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  14

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    pago_curso
    (
        init => init
        upgrade => upgrade
        enroll => enroll
        complete_class => complete_class
        sign_class => sign_class
        calculateProportionalPayment => calculate_proportional_payment
        getCurrentFunds => get_current_funds
        getTeacher => teacher
        getStudents => students
        getCourseFee => course_fee
        getTotalClasses => total_classes
        getClassesCompleted => classes_completed
        getCourseStatus => course_status
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
